/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedEnviarBrechoRouteImport } from './routes/_authenticated/enviar-brecho'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as BrechosIndexRouteImport } from './routes/brechos.index'
import { Route as BrechosIdRouteImport } from './routes/brechos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEnviarBrechoRoute =
  AuthenticatedEnviarBrechoRouteImport.update({
    id: '/enviar-brecho',
    path: '/enviar-brecho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BrechosIndexRoute = BrechosIndexRouteImport.update({
  id: '/brechos/',
  path: '/brechos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrechosIdRoute = BrechosIdRouteImport.update({
  id: '/brechos/$id',
  path: '/brechos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/enviar-brecho': typeof AuthenticatedEnviarBrechoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/brechos/$id': typeof BrechosIdRoute
  '/brechos/': typeof BrechosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/enviar-brecho': typeof AuthenticatedEnviarBrechoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/brechos/$id': typeof BrechosIdRoute
  '/brechos': typeof BrechosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/_authenticated/enviar-brecho': typeof AuthenticatedEnviarBrechoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/brechos/$id': typeof BrechosIdRoute
  '/brechos/': typeof BrechosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categorias'
    | '/criar-conta'
    | '/entrar'
    | '/enviar-brecho'
    | '/perfil'
    | '/brechos/$id'
    | '/brechos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/categorias'
    | '/criar-conta'
    | '/entrar'
    | '/enviar-brecho'
    | '/perfil'
    | '/brechos/$id'
    | '/brechos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/categorias'
    | '/criar-conta'
    | '/entrar'
    | '/_authenticated/enviar-brecho'
    | '/_authenticated/perfil'
    | '/brechos/$id'
    | '/brechos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  CategoriasRoute: typeof CategoriasRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  BrechosIdRoute: typeof BrechosIdRoute
  BrechosIndexRoute: typeof BrechosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/enviar-brecho': {
      id: '/_authenticated/enviar-brecho'
      path: '/enviar-brecho'
      fullPath: '/enviar-brecho'
      preLoaderRoute: typeof AuthenticatedEnviarBrechoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/brechos/': {
      id: '/brechos/'
      path: '/brechos'
      fullPath: '/brechos/'
      preLoaderRoute: typeof BrechosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brechos/$id': {
      id: '/brechos/$id'
      path: '/brechos/$id'
      fullPath: '/brechos/$id'
      preLoaderRoute: typeof BrechosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEnviarBrechoRoute: typeof AuthenticatedEnviarBrechoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEnviarBrechoRoute: AuthenticatedEnviarBrechoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  CategoriasRoute: CategoriasRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  BrechosIdRoute: BrechosIdRoute,
  BrechosIndexRoute: BrechosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
